settings:
  name: SnapCenter Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: All Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: SnapCenter Service docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about SnapCenter Service
          url: /concept-overview-architecture-limitation-functionalities-snapcenter-service.html
        - title: Quick Start
          url: /reference-get-started-snapcenter-service.html
        - title: Prerequisites to create Connector and enable SnapCenter Service
          url: /reference-prerequisites-azure-connector-snapcenter-service.html
        - title: Create a Connector in Azure for SnapCenter Service
          url: /task-create-azure-connector-user-consent-snapcenter-service.html
        - title: Enable SnapCenter Service for Azure NetApp Files
          url: /task-enable-snapcenter-service-azure-netapp-files.html
        - title: Install the HDBSQL client
          url: /task-install-hdbsql-client-snapcenter-service.html
    - title: Use SnapCenter Service to protect SAP HANA systems
      entries:
        - title: Add SAP HANA systems
          url: /task-add-sap-hana-systems-non-data-volumes-snapcenter-service.html
        - title: Back up SAP HANA systems
          url: /task-create-backup-ondemand-policies-schedule-sap-hana.html
        - title: Restore SAP HANA systems
          url: /task-restore-sap-hana-systems.html
        - title: Manage operations
          url: /reference-manage-dashboard-monitor-notification-snapcenter-service.html
        - title: Troubleshoot issues
          url: /reference-troubleshoot-solution-issue.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
homepage:
  tiles:
    - title: Get started
      links:
        - title: Whats's new
          url: /whats-new.html
        - title: Learn about SnapCenter Service
          url: /concept-overview-architecture-limitation-functionalities-snapcenter-service.html
        - title: Quick Start
          url: /reference-get-started-snapcenter-service.html
    - title: Enable SnapCenter Service
      links:
        - title: Prerequisites
          url: /reference-prerequisites-azure-connector-snapcenter-service.html
        - title: Create a Connector
          url: /task-create-azure-connector-user-consent-snapcenter-service.html
        - title: Enable SnapCenter Service
          url: /task-enable-snapcenter-service-azure-netapp-files.html
        - title: Install the HDBSQL client
          url: /task-install-hdbsql-client-snapcenter-service.html
    - title: Protect SAP HANA systems
      links:
        - title: Add SAP HANA systems
          url: /task-add-sap-hana-systems-non-data-volumes-snapcenter-service.html
        - title: Back up SAP HANA systems
          url: /task-create-backup-ondemand-policies-schedule-sap-hana.html
        - title: Restore SAP HANA systems
          url: /task-restore-sap-hana-systems.html
    - title: Knowledge & support
      links:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
