settings:
  name: "Product Name"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: SnapCenter Service docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about SnapCenter Service
          url: /overview-architecture-limitation-functionalities-snapcenter-service.html
        - title: Quick Start
          url: /get-started-snapcenter-service.html
        - title: Prerequisites to create Connector and enable SnapCenter Service
          url: /prerequisites-azure-connector-snapcenter-service.html
        - title: Create a Connector in Azure for SnapCenter Service
          url: /create-azure-connector-user-consent-snapcenter-service.html
        - title: Enable SnapCenter Service for Azure NetApp Files
          url: /enable-snapcenter-service-azure-netapp-files.html
        - title: Install the HDBSQL client
          url: install-hdbsql-client-snapcenter-service.html
    - title: Use SnapCenter Service to protect SAP HANA systems
      entries:
        - title: Add SAP HANA systems
          url: /add-sap-hana-systems-non-data-volumes-snapcenter-service.html
        - title: Back up SAP HANA systems
          url: /create-backup-ondemand-policies-schedule-sap-hana.html
        - title: Restore SAP HANA systems
          url: /restore-sap-hana-systems.html
        - title: Manage operations
          url: /manage-dashboard-monitor-notification-snapcenter-service.html
        - title: Troubleshoot issues
          url: /troubleshoot-solution-issue.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
    - title: <tile name>
      links:
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
